# Generated by Django 5.2.7 on 2025-11-05 14:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('furniture', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='furniture',
            options={'verbose_name': 'Furniture', 'verbose_name_plural': 'Furniture'},
        ),
        migrations.AlterField(
            model_name='furniture',
            name='provider',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='furniture', to='furniture.provider'),
        ),
        migrations.AlterModelTable(
            name='furniture',
            table='furniture',
        ),
    ]
